import { useBookmarkManagerData } from './useBookmarkManagerData'
import { useBookmarkManagerUi } from './useBookmarkManagerUi'

export function useBookmarkManagerPage() {
  const data = useBookmarkManagerData()
  const ui = useBookmarkManagerUi(data)

  return {
    bookmarkTree: data.bookmarkTree,
    bookmarkType: data.bookmarkType,
    closeEditDialog: data.closeEditDialog,
    collapsePanel: ui.collapsePanel,
    createNewBookmark: data.createNewBookmark,
    currentBookmark: data.currentBookmark,
    currentEditBookmark: data.currentEditBookmark,
    currentPath: ui.currentPath,
    contextMenuStyle: ui.contextMenuStyle,
    defaultExpandedKeys: data.defaultExpandedKeys,
    dragIndicatorTop: ui.dragIndicatorTop,
    dragInsertPosition: ui.dragInsertPosition,
    dragOverTarget: ui.dragOverTarget,
    exportBookmarks: data.exportBookmarks,
    fileInput: data.fileInput,
    filteredBookmarks: data.filteredBookmarks,
    focusedItemId: data.focusedItemId,
    folderTreeOptions: data.folderTreeOptions,
    getBookmarkDisplayIcon: data.getBookmarkDisplayIcon,
    goBackToHome: ui.goBackToHome,
    handleBookmarkIconError: data.handleBookmarkIconError,
    handleBreadcrumbClick: ui.handleBreadcrumbClick,
    handleContainerDragOver: ui.handleContainerDragOver,
    handleDeleteBookmark: ui.handleDeleteBookmark,
    handleDragEnd: ui.handleDragEnd,
    handleDragLeave: ui.handleDragLeave,
    handleDragOver: ui.handleDragOver,
    handleDragStart: ui.handleDragStart,
    handleDrop: ui.handleDrop,
    handleEditBookmark: ui.handleEditBookmark,
    handleFileChange: data.handleFileChange,
    handleNodeExpand: ui.handleNodeExpand,
    handleSearch: ui.handleSearch,
    handleSelect: ui.handleSelect,
    isContextMenuOpen: ui.isContextMenuOpen,
    isCreateMode: data.isCreateMode,
    isDropdownOpen: ui.isDropdownOpen,
    isEditDialogOpen: data.isEditDialogOpen,
    isMobile: ui.isMobile,
    isPanelExpanded: ui.isPanelExpanded,
    leftPanelWidth: ui.leftPanelWidth,
    openBookmark: ui.openBookmark,
    openContextMenu: ui.openContextMenu,
    openFolder: ui.openFolder,
    renderExpandIcon: ui.renderExpandIcon,
    renderTreeLabel: ui.renderTreeLabel,
    resetDragState: ui.resetDragState,
    saveBookmarkChanges: data.saveBookmarkChanges,
    searchQuery: data.searchQuery,
    selectedBookmarkId: data.selectedBookmarkId,
    selectedFolder: data.selectedFolder,
    selectedKeysRef: ui.selectedKeysRef,
    setFocusedItemId: ui.setFocusedItemId,
    showLeftPanel: ui.showLeftPanel,
    startResize: ui.startResize,
    togglePanel: ui.togglePanel,
    triggerImportBookmarks: data.triggerImportBookmarks,
  }
}
